name: Deploy Server

on:
  push:
    branches: [ main ]

jobs:
  deploy_test:
    runs-on: self-hosted

    steps:
      - name: Deploy to Remote Host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd /home/tannp/telegram-bot-github-notify
            git reset --hard HEAD
            git pull origin main
            composer install
